//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChromiumLauncher {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class LauncherConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static LauncherConfig defaultInstance = ((LauncherConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LauncherConfig())));
        
        public static LauncherConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ChromiumPath {
            get {
                return ((string)(this["ChromiumPath"]));
            }
            set {
                this["ChromiumPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastVersion {
            get {
                return ((string)(this["LastVersion"]));
            }
            set {
                this["LastVersion"] = value;
            }
        }
    }
}
